### ISSUE TITLE
keras_vision_model_ResNet50_test fails with weights='imagenet'

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#1660]
I tried using `ResNet50` with `weights=imagenet` in a Colab notebook using the `vmla` driver/backend and hit issues when trying to call the `predict` function on the compiled module. I see the same errors when I run `keras_vision_model_ResNet50_test` with some local changes.

Test file: https://github.com/google/iree/blob/master/integrations/tensorflow/e2e/keras_vision_model_test.py

Local changes I have when trying:

```
-INPUT_SHAPE = [1, 32, 32, 3]
+INPUT_SHAPE = [1, 224, 224, 3]

-        weights=None, include_top=False, input_shape=INPUT_SHAPE[1:])
+        weights="imagenet", include_top=True, input_shape=tuple(INPUT_SHAPE[1:]))
```

(the test passes with `weights=None` and the other changes)

Error message appears to be `Parameter 0 contains a reference to the wrong type; have hal.buffer but expected hal.allocator`, in context:

```
$ bazel test integrations/tensorflow/e2e:keras_vision_model_ResNet50_test --test_output=all
...
I0424 16:49:53.328980 139798114543424 tf_test_utils.py:520] Using backends from command line: tf,iree_vmla
...
I0424 16:50:19.922265 139798114543424 tf_test_utils.py:91] Saving raw TF input MLIR to: /usr/local/google/home/scotttodd/.cache/bazel/_bazel_scotttodd/9e82052937ca42451e1b3d0e47f9949a/sandbox/linux-sandbox/10517/execroot/iree_core/_tmp/ccf1a5e1919931ba41e4207858fa92c2/AppTest/raw_vmla.mlir
I0424 16:50:21.032403 139798114543424 tf_test_utils.py:101] Saving IREE input MLIR to: /usr/local/google/home/scotttodd/.cache/bazel/_bazel_scotttodd/9e82052937ca42451e1b3d0e47f9949a/sandbox/linux-sandbox/10517/execroot/iree_core/_tmp/ccf1a5e1919931ba41e4207858fa92c2/AppTest/input_vmla.mlir
I0424 16:50:23.630982 139798114543424 tf_test_utils.py:109] Saving compiled IREE module to: /usr/local/google/home/scotttodd/.cache/bazel/_bazel_scotttodd/9e82052937ca42451e1b3d0e47f9949a/sandbox/linux-sandbox/10517/execroot/iree_core/_tmp/ccf1a5e1919931ba41e4207858fa92c2/AppTest/compiled_vmla.vmfb
[ RUN      ] AppTest.test_application
E ./iree/base/api_util.h:30] INVALID_ARGUMENT: Parameter 0 contains a reference to the wrong type; have hal.buffer but expected hal.allocator (N4iree2vm3refI18iree_hal_allocatorEE); while executing hal.allocator.allocate.const
Created IREE driver vmla: <pyiree.rt.binding.HalDriver object at 0x7f225413edb0>
SystemContext driver=<pyiree.rt.binding.HalDriver object at 0x7f225413edb0>
[  FAILED  ] AppTest.test_application
[ RUN      ] AppTest.test_session
[  SKIPPED ] AppTest.test_session
======================================================================
ERROR: test_application (__main__.AppTest)
test_application (__main__.AppTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/scotttodd/.cache/bazel/_bazel_scotttodd/9e82052937ca42451e1b3d0e47f9949a/sandbox/linux-sandbox/10517/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/keras_vision_model_ResNet50_test.runfiles/iree_core/integrations/tensorflow/e2e/keras_vision_model_test.py", line 103, in test_application
    self.modules.applications.all.predict(input_data).print().assert_all_close(
  File "/usr/local/google/home/scotttodd/.cache/bazel/_bazel_scotttodd/9e82052937ca42451e1b3d0e47f9949a/sandbox/linux-sandbox/10517/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/keras_vision_model_ResNet50_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 305, in __call__
    for backend, f in self._backend_function_dict.items()
  File "/usr/local/google/home/scotttodd/.cache/bazel/_bazel_scotttodd/9e82052937ca42451e1b3d0e47f9949a/sandbox/linux-sandbox/10517/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/keras_vision_model_ResNet50_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 305, in <dictcomp>
    for backend, f in self._backend_function_dict.items()
  File "/usr/local/google/home/scotttodd/.cache/bazel/_bazel_scotttodd/9e82052937ca42451e1b3d0e47f9949a/sandbox/linux-sandbox/10517/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/keras_vision_model_ResNet50_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 264, in __call__
    return self._f(*args)
  File "/usr/local/google/home/scotttodd/.cache/bazel/_bazel_scotttodd/9e82052937ca42451e1b3d0e47f9949a/sandbox/linux-sandbox/10517/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/keras_vision_model_ResNet50_test.runfiles/iree_core/bindings/python/pyiree/rt/system_api.py", line 130, in __call__
    self._context._vm_context.invoke(self._vm_function, inputs, results)
ValueError: Error invoking function: 3
```

**Comment by benvanik** [comment]
probably related to https://github.com/google/iree/issues/1620

**Comment by benvanik** [comment]
try running with assertions on

**Comment by ScottTodd** [comment]
I'm not seeing more useful logs with `-c dbg` or `--copt=-UNDEBUG`. Is there a different way to enable assertions?

**Comment by benvanik** [comment]
no clue - I just build in cmake's Debug configuration

**Comment by benvanik** [comment]
you can also add a log line here, I suspect it's the same issue: https://github.com/google/iree/issues/1620#issuecomment-619140638

**Comment by ScottTodd** [comment]
> no clue - I just build in cmake's Debug configuration

Can't build this test with CMake since it uses TensorFlow, but I could dump the `.mlir` and run that through tools built with CMake.

**Comment by benvanik** [comment]
ah that's what I do - I'm using lei's attached mlir from that bug for example
![image](https://user-images.githubusercontent.com/75337/80245662-ee662080-861f-11ea-9d6e-1a910f646c85.png)

**Comment by hanhanW** [comment]
The way I tried is to run py script first, so I'll get the mlir file from `Saving IREE input MLIR to:...`. After that, I build `iree-run-mlir` with whatever flag I want, and run the command `iree-run-mlir -iree-hal-target-backends=vmla PATH_TO_MLIR_FILE -input-value="1x32x32x3xf32=..."`.

**Comment by benvanik** [comment]
It would be nice to have a python flag that spits out the right command line (with the same input values) - then we can ensure output matches while debugging easier.

**Comment by ScottTodd** [comment]
This particular model seems to fail with "real" weights but succeed with placeholder weights (replacing `dense<".+">` with `dense<1.2>`, taking the input `.mlir` file size from 200MB to 200KB).

**Comment by hanhanW** [comment]
Now we have the test on tf, and I got the same error.

Instruction to repro:
`bazel run integrations/tensorflow/e2e:keras_vision_model_imagenet_top_0_ResNet50_test -- --override_backends=iree_vmla`

The saved MLIR file: https://drive.google.com/file/d/1tcf8Id1GdeKov7urACX69jPi_C7UNNJf/view?usp=sharing

$ build iree-run-mlir
$ iree-run-mlir -iree-hal-target-backends=vmla ~/resnet_imagenet.mlir -input-value="1x224x224x3xf32=0"

Error log:
```
INVALID_ARGUMENT: Parameter 0 contains a reference to the wrong type; have hal.buffer but expected hal.allocator (N4iree2vm3refI18iree_hal_allocatorEE); while executing hal.allocator.allocate.const
```

My guess is the constant is too large. There are too many elements so the allocation failed?

**Comment by hanhanW** [comment]
Oh, just saw the mail said that it's a VM register allocation problem.
