### ISSUE TITLE
`PYTHON_BIN` only dictates what python version is used at compile time.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#1875]
The `PYTHON_BIN` environment variable is supposed to dictate which version of python to use in IREE, however system python3 (`/usr/bin/python3`) is used regardless of this value at runtime. This leads to errors like the one below if `PYTHON_BIN` doesn't point to the system's python3 and the version of python that `PYTHON_BIN` points to is different from the system's python3. This can easily be replicated in a docker image.

```shell
FAIL: //bindings/python/pyiree/rt:vm_test (see /root/.cache/bazel/_bazel_root/7f6012756177e412d34fb352ad498c5a/execroot/iree_core/bazel-out/k8-opt/testlogs/bindings/python/pyiree/rt/vm_test/test.log)
INFO: From Testing //bindings/python/pyiree/rt:vm_test:
==================== Test output for //bindings/python/pyiree/rt:vm_test:
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/7f6012756177e412d34fb352ad498c5a/sandbox/processwrapper-sandbox/2668/execroot/iree_core/bazel-out/k8-opt/bin/bindings/python/pyiree/rt/vm_test.runfiles/iree_core/bindings/python/pyiree/rt/vm_test.py", line 20, in <module>
    from pyiree import compiler
  File "/root/.cache/bazel/_bazel_root/7f6012756177e412d34fb352ad498c5a/sandbox/processwrapper-sandbox/2668/execroot/iree_core/bazel-out/k8-opt/bin/bindings/python/pyiree/rt/vm_test.runfiles/iree_core/bindings/python/pyiree/compiler/__init__.py", line 21, in <module>
    from . import binding as binding
ImportError: Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609].
```

The original discussion about how this can be fixed is in [the python section of IREE discord](https://discord.com/channels/689900678990135345/706175572920762449/708435150689665044).

**Comment by benvanik** [comment]
Obsolete?

**Comment by phoenix-meadowlark** [comment]
Bazel python can't have bugs if bazel python doesn't exist :)
