### ISSUE TITLE
Failing tensorflow e2e tests

### ISSUE THREAD

**Issue by bondhugula** [google/iree#2008]
Hi,

I have commit 95eb2eb55baa696d19cfe002f74721e40d468ad7 as of May 21.  With bazel test under opt for //integrations/tensorflow/e2e:all, I see 7 failing tests. Some details below. Are these expected?

```
//integrations/tensorflow/e2e:batch_norm_test                   (cached) PASSED in 5.5s
//integrations/tensorflow/e2e:broadcasting_test                 (cached) PASSED in 5.8s
//integrations/tensorflow/e2e:control_flow_test                 (cached) PASSED in 6.2s
//integrations/tensorflow/e2e:depth_conv_test                   (cached) PASSED in 6.2s
//integrations/tensorflow/e2e:dynamic_mlp_relu_test             (cached) PASSED in 5.2s
//integrations/tensorflow/e2e:dynamic_mlp_test                  (cached) PASSED in 5.8s
//integrations/tensorflow/e2e:fill_test                         (cached) PASSED in 5.2s
//integrations/tensorflow/e2e:keras_lstm_test                   (cached) PASSED in 7.3s
//integrations/tensorflow/e2e:linspace_test                     (cached) PASSED in 5.8s
//integrations/tensorflow/e2e:mandelbrot_test                   (cached) PASSED in 7.7s
//integrations/tensorflow/e2e:matrix_ops_test                   (cached) PASSED in 7.3s
//integrations/tensorflow/e2e:resource_ops_test                 (cached) PASSED in 5.5s
//integrations/tensorflow/e2e:ring_buffer_test                  (cached) PASSED in 6.1s
//integrations/tensorflow/e2e:sliding_window_test               (cached) PASSED in 5.8s
//integrations/tensorflow/e2e:strings_test                      (cached) PASSED in 5.3s
//integrations/tensorflow/e2e:tensorlist_test                   (cached) PASSED in 6.2s
//integrations/tensorflow/e2e:conv_test                                  FAILED in 5.5s
  /data/uday/136ce1be51bd5797ace9540c1c80b503/execroot/iree_core/bazel-out/k8-opt/testlogs/integrations/tensorflow/e2e/conv_test/test.log
//integrations/tensorflow/e2e:exported_names_test                        FAILED in 3.9s
  /data/uday/136ce1be51bd5797ace9540c1c80b503/execroot/iree_core/bazel-out/k8-opt/testlogs/integrations/tensorflow/e2e/exported_names_test/test.log
//integrations/tensorflow/e2e:gather_test                                FAILED in 4.1s
  /data/uday/136ce1be51bd5797ace9540c1c80b503/execroot/iree_core/bazel-out/k8-opt/testlogs/integrations/tensorflow/e2e/gather_test/test.log
//integrations/tensorflow/e2e:keras_lstm_static_test                     FAILED in 8.0s
  /data/uday/136ce1be51bd5797ace9540c1c80b503/execroot/iree_core/bazel-out/k8-opt/testlogs/integrations/tensorflow/e2e/keras_lstm_static_test/test.log
//integrations/tensorflow/e2e:math_test                                  FAILED in 4.0s
  /data/uday/136ce1be51bd5797ace9540c1c80b503/execroot/iree_core/bazel-out/k8-opt/testlogs/integrations/tensorflow/e2e/math_test/test.log
//integrations/tensorflow/e2e:simple_arithmetic_test                     FAILED in 3.9s
  /data/uday/136ce1be51bd5797ace9540c1c80b503/execroot/iree_core/bazel-out/k8-opt/testlogs/integrations/tensorflow/e2e/simple_arithmetic_test/test.log
//integrations/tensorflow/e2e:simple_stateful_test                       FAILED in 4.5s
  /data/uday/136ce1be51bd5797ace9540c1c80b503/execroot/iree_core/bazel-out/k8-opt/testlogs/integrations/tensorflow/e2e/simple_stateful_test/test.log
```

From one of the files, I see errors like these:
```
Created IREE driver vmla: <pyiree.rt.binding.HalDriver object at 0x7f2dd054a230>
SystemContext driver=<pyiree.rt.binding.HalDriver object at 0x7f2dd054a230>
Created IREE driver vulkan: <pyiree.rt.binding.HalDriver object at 0x7f2dd054aeb0>
[  FAILED  ] MathTest.test_mod
[ RUN      ] MathTest.test_session
[  SKIPPED ] MathTest.test_session
======================================================================
ERROR: test_abs (__main__.MathTest)
test_abs (__main__.MathTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/uday/136ce1be51bd5797ace9540c1c80b503/sandbox/linux-sandbox/8771/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/math_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 631, in setUp
    self.modules = _instantiate_modules(self.compiled_modules)
  File "/data/uday/136ce1be51bd5797ace9540c1c80b503/sandbox/linux-sandbox/8771/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/math_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 414, in _instantiate_modules
    for (_, module_dict) in compiled_modules_dict.items()
  File "/data/uday/136ce1be51bd5797ace9540c1c80b503/sandbox/linux-sandbox/8771/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/math_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 414, in <listcomp>
    for (_, module_dict) in compiled_modules_dict.items()
  File "/data/uday/136ce1be51bd5797ace9540c1c80b503/sandbox/linux-sandbox/8771/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/math_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 409, in instantiate_backends
    *[m.instantiate() for m in module_dict.values()])
  File "/data/uday/136ce1be51bd5797ace9540c1c80b503/sandbox/linux-sandbox/8771/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/math_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 409, in <listcomp>
    *[m.instantiate() for m in module_dict.values()])
  File "/data/uday/136ce1be51bd5797ace9540c1c80b503/sandbox/linux-sandbox/8771/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/math_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 233, in instantiate
    self._iree_module)
  File "/data/uday/136ce1be51bd5797ace9540c1c80b503/sandbox/linux-sandbox/8771/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/math_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 245, in __init__
    self._system_config = rt.Config(driver_name=backend.iree_driver)
  File "/data/uday/136ce1be51bd5797ace9540c1c80b503/sandbox/linux-sandbox/8771/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/math_test.runfiles/iree_core/bindings/python/pyiree/rt/system_api.py", line 97, in __init__
    self.device = self.driver.create_default_device()
RuntimeError: Error creating default device: 14
```

On this note, while I was trying to run these tests, I first got errors on missing modules absl and then tensorflow, which I then installed via pip. However, I was expecting at least tensorflow to have been found and used from the build itself. The instructions here: https://google.github.io/iree/GetStarted/LinuxBazel don't ask for these modules to have already been installed.

**Comment by ScottTodd** [comment]
These failures look like Vulkan device creation is failing. As such, they are expected when using the default flags without a configured Vulkan driver on the system. If you have partial Vulkan support, you can set `VK_LOADER_DEBUG=all` to get more information (see also https://google.github.io/iree/GetStarted/LinuxVulkan and https://google.github.io/iree/GetStarted/GenericVulkanSetup).

To filter out these tests, you can also copy what our GitHub actions CI does: https://github.com/google/iree/blob/399101a4e1018b4f38fbd78ca98deb76b5ccb3ea/.github/workflows/bazel_build_integrations.yml#L53-L59

---

### Python modules

The Python docs (https://google.github.io/iree/GetStarted/Python) mention installing `tf-nightly` using pip. There are notes at the top and bottom of the LinuxBazel doc mentioning the Python docs, as I wanted to keep the core docs as simple as possible.

We could pull TensorFlow from the build itself, though this would increase build times (significantly?). The place to add that dep would be here: https://github.com/google/iree/blob/399101a4e1018b4f38fbd78ca98deb76b5ccb3ea/bindings/python/build_defs.oss.bzl#L42-L44
We use a different version of that file in Google's upstream repo that lists TensorFlow and absl there.

---

### Test defaults, flags, etc.

The TensorFlow integration tests in that directory support multiple ways of filtering: https://github.com/google/iree/blob/master/integrations/tensorflow/e2e/README.md. We've iterated a few times there, to support both developers enabling/disabling backends during development and to support continuous integration machines filtering by which backends they want to run tests for (which should be a subset of which backends they support).

Right now backends are "opt-out", and the default is to run on all backends that each test specifies. This is somewhat for historical reasons, and I could see this changing as we build out other ways to filter the build (e.g. https://github.com/google/iree/pull/1831 for CMake).
