### ISSUE TITLE
`linspace_test.py` fails due to tf.ConcatV2 lowering failure

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#2082]
The `//integrations/tensorflow/e2e:linspace_test` fails due to the following error:

```bazel
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //integrations/tensorflow/e2e:linspace_test
-----------------------------------------------------------------------------
2020-06-01 20:36:00.466903: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-06-01 20:36:00.466924: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Warning, backtrace signal handler for signal 11 overwrote previous handler.
Warning, backtrace signal handler for signal 6 overwrote previous handler.
Warning, backtrace signal handler for signal 7 overwrote previous handler.
Warning, backtrace signal handler for signal 4 overwrote previous handler.
Warning, backtrace signal handler for signal 8 overwrote previous handler.
Running tests under Python 3.6.9: /usr/bin/python3
I0601 20:36:01.344614 140710301476672 tf_test_utils.py:536] No backend overrides.
2020-06-01 20:36:01.420866: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-06-01 20:36:01.420887: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-06-01 20:36:01.420901: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2020-06-01 20:36:01.421009: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-06-01 20:36:01.442769: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 4008000000 Hz
2020-06-01 20:36:01.443666: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4e50e50 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-01 20:36:01.443677: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
INFO:tensorflow:Assets written to: /tmp/tmpk0xmrnk7/assets
I0601 20:36:01.510439 140710301476672 builder_impl.py:775] Assets written to: /tmp/tmpk0xmrnk7/assets
2020-06-01 20:36:01.513013: I external/org_tensorflow/tensorflow/cc/saved_model/bundle_v2.cc:32] Reading SavedModel from: /tmp/tmpk0xmrnk7
2020-06-01 20:36:01.513269: I external/org_tensorflow/tensorflow/cc/saved_model/bundle_v2.cc:55] Reading SavedModel debug info (if present) from: /tmp/tmpk0xmrnk7
I0601 20:36:01.570157 140710301476672 tf_test_utils.py:91] Saving raw TF input MLIR to: /[irrelevant-base-path]/iree_core/_tmp/13947bbfeea932cff440b306e7162951/LinspaceTest/raw_vmla.mlir
I0601 20:36:01.582814 140710301476672 tf_test_utils.py:101] Saving IREE input MLIR to: /[irrelevant-base-path]/iree_core/_tmp/13947bbfeea932cff440b306e7162951/LinspaceTest/input_vmla.mlir
[  FAILED  ] setUpClass (__main__.LinspaceTest)
======================================================================
ERROR: setUpClass (__main__.LinspaceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/[irrelevant-base-path]/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/linspace_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 623, in setUpClass
    for backend in backends
  File "/[irrelevant-base-path]/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/linspace_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 623, in <listcomp>
    for backend in backends
  File "/[irrelevant-base-path]/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/linspace_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 167, in create
    return compiled_module_class(ctor, exported_names, backend)
  File "/[irrelevant-base-path]/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/linspace_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 234, in __init__
    target_backends=backend.iree_compiler_targets)
  File "/[irrelevant-base-path]/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/linspace_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 128, in save_and_compile_tf_module
    return compile_from_path(sm_path)
  File "/[irrelevant-base-path]/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/linspace_test.runfiles/iree_core/integrations/tensorflow/bindings/python/pyiree/tf/support/tf_test_utils.py", line 105, in compile_from_path
    compiled_module = compiler_module.compile(target_backends=target_backends)
RuntimeError: Error compiling IREE module:

[ERROR]: 'tf.ConcatV2' op operand #0 must be tensor of tf.dtype values, but got '!hal.buffer'
  at: function.py:2838:0                ( /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py:2838:0 )
  at: function.py:3195:0                ( /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py:3195:0 )
  at: function.py:3057:0                ( /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py:3057:0 )
  at: func_graph.py:981:0               ( /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py:981:0 )
  at: def_function.py:595:0             ( /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py:595:0 )
  at: function.py:3717:0                ( /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py:3717:0 )
  at: func_graph.py:964:0               ( /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py:964:0 )
  at: linspace_test.py:33:0             ( iree_core/integrations/tensorflow/e2e/linspace_test.py:33:0 )
  at: dispatch.py:201:0         ( /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201:0 )
  @'linspace/concat@__inference_linspace_70':
(...
  at: math_ops.py:207:0         ( /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:207:0 )
)


[ERROR]: A failure has been detected while processing the MLIR module, a reproducer has been generated in '/[irrelevant-base-path]/iree_core/_tmp/13947bbfeea932cff440b306e7162951/LinspaceTest/linspace_reproducer.mlir'
  [unknown location]


----------------------------------------------------------------------
Ran 0 tests in 0.267s

FAILED (errors=1)
```

For now this test is disabled in the OSS CI.

**Comment by GMNGeoffrey** [comment]
@not-jenni I think you added this test. Any idea what's going on here? I think it passes internally so this might be some dependency diff

**Comment by not-jenni** [comment]
Yes, the test is still passing internally but i haven’t looked at it much from the oss side.  I think originally it was disabled because Vulkan was unsupported, but it looks like that is no longer the case. @rsuderman do you know more about tf.ConcatV2 ?

**Comment by antiagainst** [comment]
This is failing for VMLA so not related to GPU at all? But there are quite some warnings related to CUDA.. Seems TF wasn't properly configured. It might be helpful to paste the repro.

**Comment by GMNGeoffrey** [comment]
If I had to guess, I'd say this is another case of needing to include more of TF so we can get more kernels, which are required for constant folding that will make this operation go away :vomiting_face:

**Comment by phoenix-meadowlark** [comment]
Pinging this because it is still unresolved. I tagged the `linspace_test` as manual in #3257 because it doesn't work on kokoro or in (most) OSS environments.

**Comment by not-jenni** [comment]
@rsuderman Do you know anything about the lowering for tf.ConcatV2 ?

**Comment by rsuderman** [comment]
Yup, I've been working on this the last couple days. There are some more changes I need to do on the Tensorflow before the IREE level fix will work but should be done early next week.

**Comment by benvanik** [comment]
Obsolete?

**Comment by phoenix-meadowlark** [comment]
It is! Looks like it was fixed by https://github.com/google/iree/commit/0b836b74415d005691304d8faf6eef4f2612fc89.
