### ISSUE TITLE
RefPtrTest.MoveCompatible is failing under ASAN

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#3451]
```
[ RUN      ] RefPtrTest.MoveCompatible
=================================================================
==1928==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x602000000f10 in thread T0:
  object passed to delete has wrong type:
  size of the allocated type:   12 bytes;
  size of the deallocated type: 8 bytes.
    #0 0x55fc331bc062 in operator delete(void*, unsigned long) third_party/llvm/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:172:3
    #1 0x7fdb231a895e in iree::RefObject<iree::(anonymous namespace)::RefPtrTest_MoveCompatible_Test::TestBody()::MyBaseType>::delete_thunk<iree::(anonymous namespace)::RefPtrTest_MoveCompatible_Test::TestBody()::MyBaseType, false>::Delete(iree::(anonymous namespace)::RefPtrTest_MoveCompatible_Test::TestBody()::MyBaseType*) third_party/iree/iree/base/ref_ptr.h:281:9
    #2 0x7fdb231a8928 in iree::ref_ptr_release_ref(iree::(anonymous namespace)::RefPtrTest_MoveCompatible_Test::TestBody()::MyBaseType*) third_party/iree/iree/base/ref_ptr.h:301:5
    #3 0x7fdb231a8330 in ~ref_ptr third_party/iree/iree/base/ref_ptr.h:127:14
    #4 0x7fdb231a8330 in iree::(anonymous namespace)::RefPtrTest_MoveCompatible_Test::TestBody() third_party/iree/iree/base/ref_ptr_test.cc:238:1
...
0x602000000f10 is located 0 bytes inside of 12-byte region [0x602000000f10,0x602000000f1c)
allocated by thread T0 here:
    #0 0x55fc331bb3dd in operator new(unsigned long) third_party/llvm/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:99:3
    #1 0x7fdb231a86b3 in iree::ref_ptr<iree::(anonymous namespace)::RefPtrTest_MoveCompatible_Test::TestBody()::MyTypeB> iree::make_ref<iree::(anonymous namespace)::RefPtrTest_MoveCompatible_Test::TestBody()::MyTypeB>() third_party/iree/iree/base/ref_ptr.h:41:21
    #2 0x7fdb231a80d3 in iree::(anonymous namespace)::RefPtrTest_MoveCompatible_Test::TestBody() third_party/iree/iree/base/ref_ptr_test.cc:235:10
...
```

**Comment by benvanik** [comment]
I think this issue always existed (deleter of a different type used) but was not caught by asan because the size was the same between the two types. Adding a virtual destructor may be enough to get it to work.

**Comment by ScottTodd** [comment]
I wasn't able to repro using open source tools, so tested internally: https://github.com/google/iree/pull/3464. Virtual destructor indeed makes the ASAN error go away.
