### ISSUE TITLE
Bazel invocation error on release packages (no config 'release')

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#4960]
```
      + sh -c 'python ./main_checkout/build_tools/github_actions/build_dist.py py-xla-compiler-tools-pkg'
  Starting local Bazel server and connecting to it...
  ERROR: Config value 'release' is not defined in any .rc file
  Traceback (most recent call last):
    File "./main_checkout/build_tools/github_actions/build_dist.py", line 342, in <module>
      build_py_xla_compiler_tools_pkg()
    File "./main_checkout/build_tools/github_actions/build_dist.py", line 233, in build_py_xla_compiler_tools_pkg
      binpath = bazel_build_tf_binary("//iree_tf_compiler:iree-import-xla")
    File "./main_checkout/build_tools/github_actions/build_dist.py", line 210, in bazel_build_tf_binary
      process = subprocess.run(cmd,
    File "/opt/python/cp38-cp38/lib/python3.8/subprocess.py", line 512, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['bazel', 'run', '--run_under=echo', '--config=release', '//iree_tf_compiler:iree-import-xla']' returned non-zero exit status 2.
```

**Comment by stellaraccident** [comment]
Looks like the issue is on ubuntu because the build matrix does not set the `needs_bazel` flag. Fails on windows/macos for a different reason.
