### ISSUE TITLE
iree_vm_native_module_t destruction logic is weird and leaking

### ISSUE THREAD

**Issue by benvanik** [google/iree#4978]
I have no clue how it works (and I wrote it) - right now we have a leak:
```
INFO: From Testing //iree/vm:native_module_test:
==================== Test output for //iree/vm:native_module_test:
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from VMNativeModuleTest
[ RUN      ] VMNativeModuleTest.Example
[       OK ] VMNativeModuleTest.Example (1 ms)
[----------] 1 test from VMNativeModuleTest (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1 ms total)
[  PASSED  ] 1 test.

=================================================================
==30146==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 248 byte(s) in 1 object(s) allocated from:
    #0 0x49bfe2 in calloc (/tmp/bazel-root/a27c228e8a23df16825b36c2fff26fb4/execroot/iree_core/bazel-out/k8-asan-dbg/bin/iree/vm/native_module_test+0x49bfe2)
    #1 0x7f2314956d26 in iree_allocator_system_allocate /proc/self/cwd/iree/base/api.c:1106:13
    #2 0x7f2314955fa6 in iree_allocator_malloc /proc/self/cwd/iree/base/api.c:1054:10
    #3 0x7f231499cbc7 in iree_vm_native_module_create /proc/self/cwd/iree/vm/native_module.c:371:3
    #4 0x4d10ea in module_b_create(iree_allocator_t, iree_vm_module**) /proc/self/cwd/./iree/vm/native_module_test.h:310:10
    #5 0x4cda5f in iree::(anonymous namespace)::VMNativeModuleTest::SetUp() /proc/self/cwd/iree/vm/native_module_test.cc:42:5
    #6 0x7f23143d0f33 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2588:12
    #7 0x7f2314399088 in testing::Test::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2600:3
    #8 0x7f231439aec4 in testing::TestInfo::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2783:11
    #9 0x7f231439c740 in testing::TestSuite::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2937:28
    #10 0x7f23143badaa in testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5631:44
    #11 0x7f23143d7532 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2588:12
    #12 0x7f23143ba0ac in testing::UnitTest::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5219:10
    #13 0x7f231497b110 in RUN_ALL_TESTS() /proc/self/cwd/external/com_google_googletest/googletest/include/gtest/gtest.h:2486:46
    #14 0x7f231497b031 in main /proc/self/cwd/iree/testing/gtest_main.cc:22:10
    #15 0x7f23140170b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: 248 byte(s) leaked in 1 allocation(s).
================================================================================
```

This is because the `module_b_destroy` is just freeing itself, and the code inside `iree_vm_native_module_destroy` isn't freeing the outer wrapper. I think I did this to allow for static module initialization, but it's clear the rule it's using (whether self has been overridden) is wrong.

Tracking here until I can get around to fixing it in case others see it too - I must be the only one running with ASAN enabled >_>

**Comment by benvanik** [comment]
I think this got fixed; this test is running and passing on the ASAN bot.
