### ISSUE TITLE
Missing symbol '__gnu_h2f_ieee' for float16 computations

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7611]
Repro:

Run the following Python script:
```
from iree import runtime as ireert
from iree.compiler import compile_str
import iree.compiler.api.driver

CODE = """
module  {
  func @main(%arg0: tensor<3xf16>) -> tensor<3xf16> {
    %0 = "mhlo.exponential"(%arg0) : (tensor<3xf16>) -> tensor<3xf16>
    return %0 : tensor<3xf16>
  }
}
"""

iree_config = ireert.system_api.Config("dylib")
compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
vm_module = ireert.VmModule.from_flatbuffer(compiled_flatbuffer)
module_object = ireert.load_vm_module(vm_module, iree_config)
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 19, in <module>
    module_object = ireert.load_vm_module(vm_module, iree_config)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/runtime/system_api.py", line 322, in load_vm_module
    return load_vm_modules(vm_module, config=config)[0]
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/runtime/system_api.py", line 315, in load_vm_modules
    context = SystemContext(vm_modules=vm_modules, config=config)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/runtime/system_api.py", line 258, in __init__
    modules=init_vm_modules)
RuntimeError: Error creating vm context with modules: /project/main_checkout/iree/hal/local/elf/elf_module.c:478: UNAVAILABLE; ELF imports one or more symbols (trying '__gnu_h2f_ieee'); imports are not supported in the platform-agnostic loader; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module.__init:260 <stdin>:4:10
      at <stdin>:3:3
```

Either IREE shouldn't generate code referring to this symbol, or it should provide it to the compiled code.

**Comment by MaheshRavishankar** [comment]
This can also be repro-ed with 

```
func @main(%arg0 : tensor<3xf16>) -> tensor<3xf16> {
  %0 = "mhlo.exponential"(%arg0) : (tensor<3xf16>) -> tensor<3xf16>
  return %0 : tensor<3xf16>
}
```

The `f16` expf function gets lowered to these calls in the LLVM backend

```
   1485:       e8 46 00 00 00          call   14d0 <__gnu_h2f_ieee@plt>
    148a:       e8 51 00 00 00          call   14e0 <expf@plt>
    148f:       e8 5c 00 00 00          call   14f0 <__gnu_f2h_ieee@plt>
```

For the f32, the `math.exp`  is not lowered to LLVM as `exp`. Isntead it is approximated away https://github.com/llvm/llvm-project/blob/94a901a50ad0d927a7c32e638053958891754955/mlir/lib/Dialect/Math/Transforms/PolynomialApproximation.cpp#L690 . Something similar is probably needed for the fp16 path.

If we need to support a whole host of half precision math, in C++ projects, I have seen the use of https://sourceforge.net/projects/half/ . We could use the approach similar to `librt` in IREE and create a library of half-precision math functions.

**Comment by benvanik** [comment]
here's some licensing friendly implementations of those two funcs we could use: https://reviews.llvm.org/D4927

**Comment by MaheshRavishankar** [comment]
Nice find! Now I have no more excuses to go and add these.
