### ISSUE TITLE
`hal.command_buffer.fill_buffer` error for bfloat16 type

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7612]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<3x10x3xbf16>, %arg1: tensor<5x3x2xbf16>) -> tensor<3x14x2xbf16> {
    %0 = mhlo.convolution(%arg0, %arg1) dim_numbers = [b, 0, f]x[0, i, o]->[b, 0, f], window = {stride = [1], pad = [[4, 4]], lhs_dilate = [1], rhs_dilate = [1], reverse = [0]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<3x10x3xbf16>, tensor<5x3x2xbf16>) -> tensor<3x14x2xbf16>
    return %0 : tensor<3x14x2xbf16>
  }
}"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:4:10: error: 'hal.command_buffer.fill_buffer' op operand #4 must be 1-bit signless integer or 8-bit signless integer or 16-bit signless integer or 32-bit signless integer or 16-bit float or 32-bit float, but got 'bf16'
    %0 = mhlo.convolution(%arg0, %arg1) dim_numbers = [b, 0, f]x[0, i, o]->[b, 0, f], window = {stride = [1], pad = [[4, 4]], lhs_dilate = [1], rhs_dilate = [1], reverse = [0]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<3x10x3xbf16>, tensor<5x3x2xbf16>) -> tensor<3x14x2xbf16>
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<3x10x3xbf16>, %arg1: tensor<5x3x2xbf16>) -> tensor<3x14x2xbf16> {
  ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by hawkinsp** [comment]
Yes and no. With an updated repro to account for MHLO changes:

```
from iree.compiler import compile_str

CODE = """
module  {
func.func @main(%arg0: tensor<3x10x3xbf16>, %arg1: tensor<5x3x2xbf16>) -> tensor<3x14x2xbf16>
{
  %0 = mhlo.convolution(%arg0, %arg1) dim_numbers = [b, 0, f]x[0, i, o]->[b, 0, f], window = {stride = [1], pad = [[4, 4]], lhs_dilate = [1], rhs_dilate = [1], reverse = [0]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64} : (tensor<3x10x3xbf16>, tensor<5x3x2xbf16>) -> tensor<3x14x2xbf16>
  return %0 : tensor<3x14x2xbf16>
}
}"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

we now crash with the following, which probably just says BF16 types aren't implemented in LLVM:

```
CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
LLVM ERROR: Cannot select: 0x7f934687e300: ch = store<(store (s16) into %ir.35 + 4)> 0x7f934687d6d0, 0x7f93468b6aa0, 0x7f93468828d8, undef:i64, <stdin>:5:8 @[ <stdin>:3:1 ]
  0x7f93468b6aa0: bf16,ch = load<(load (s16) from %ir.32 + 4)> 0x7f93468b6078, 0x7f934687dc18, undef:i64, <stdin>:5:8 @[ <stdin>:3:1 ]
    0x7f934687dc18: i64 = add 0x7f93468b2b48, Constant:i64<10>, <stdin>:5:8 @[ <stdin>:3:1 ]
      0x7f93468b2b48: i64 = add 0x7f93468afe78, 0x7f93468b2ae0, <stdin>:5:8 @[ <stdin>:3:1 ]
        0x7f93468afe78: i64,ch = load<(load (s64) from %ir.4)> 0x7f934701ae48, 0x7f93468afe10, undef:i64, <stdin>:3:1
          0x7f93468afe10: i64,ch = load<(dereferenceable load (s64) from %ir..elt19, align 16)> 0x7f934701ae48, 0x7f93468afcd8, undef:i64, <stdin>:3:1
            0x7f93468afcd8: i64 = add nuw 0x7f93468afb38, Constant:i64<32>, <stdin>:3:1
              0x7f93468afb38: i64,ch = CopyFromReg 0x7f934701ae48, Register:i64 %1
                0x7f93468afad0: i64 = Register %1
              0x7f93468afc70: i64 = Constant<32>
            0x7f93468afda8: i64 = undef
          0x7f93468afda8: i64 = undef
        0x7f93468b2ae0: i64 = shl 0x7f93468b2940, Constant:i8<1>, <stdin>:5:8 @[ <stdin>:3:1 ]
          0x7f93468b2940: i64 = add nuw nsw 0x7f93468b28d8, 0x7f93468b6690
            0x7f93468b28d8: i64 = add nuw nsw 0x7f93468b26d0, 0x7f93468b08a0
              0x7f93468b26d0: i64 = X86ISD::MUL_IMM 0x7f93468b07d0, Constant:i64<3>, <stdin>:5:8 @[ <stdin>:3:1 ]
                0x7f93468b07d0: i64,ch = load<(dereferenceable load (s32) from %ir.2, align 16), zext from i32> 0x7f934701ae48, 0x7f93468afc08, undef:i64, <stdin>:5:8 @[ <stdin>:3:1 ]
                  0x7f93468afc08: i64,ch = CopyFromReg 0x7f934701ae48, Register:i64 %2

                  0x7f93468afda8: i64 = undef
                0x7f93468b0970: i64 = Constant<3>
              0x7f93468b08a0: i64 = shl 0x7f93468b0288, Constant:i8<1>, <stdin>:5:8 @[ <stdin>:3:1 ]
                0x7f93468b0288: i64 = X86ISD::MUL_IMM 0x7f93468b0018, Constant:i64<3>, <stdin>:5:8 @[ <stdin>:3:1 ]
                  0x7f93468b0018: i64,ch = load<(dereferenceable load (s32) from %ir.2 + 4, basealign 16), zext from i32> 0x7f934701ae48, 0x7f93468b00e8, undef:i64, <stdin>:5:8 @[ <stdin>:3:1 ]


                  0x7f93468b0970: i64 = Constant<3>
                0x7f93468b3368: i8 = Constant<1>
            0x7f93468b6690: i64 = sub 0x7f93468b3300, 0x7f93468b0150, <stdin>:5:8 @[ <stdin>:3:1 ]
              0x7f93468b3300: i64 = sub 0x7f93468b0838, 0x7f93468b0150, <stdin>:5:8 @[ <stdin>:3:1 ]
                0x7f93468b0838: i64 = shl 0x7f93468b0150, Constant:i8<5>, <stdin>:5:8 @[ <stdin>:3:1 ]
                  0x7f93468b0150: i64,ch = load<(dereferenceable load (s16) from %ir.2 + 8, align 8, basealign 16), zext from i16> 0x7f934701ae48, 0x7f93468b01b8, undef:i64, <stdin>:5:8 @[ <stdin>:3:1 ]


                  0x7f93468b27a0: i8 = Constant<5>
                0x7f93468b0150: i64,ch = load<(dereferenceable load (s16) from %ir.2 + 8, align 8, basealign 16), zext from i16> 0x7f934701ae48, 0x7f93468b01b8, undef:i64, <stdin>:5:8 @[ <stdin>:3:1 ]
                  0x7f93468b01b8: i64 = add nuw 0x7f93468afc08, Constant:i64<8>, <stdin>:5:8 @[ <stdin>:3:1 ]


                  0x7f93468afda8: i64 = undef
              0x7f93468b0150: i64,ch = load<(dereferenceable load (s16) from %ir.2 + 8, align 8, basealign 16), zext from i16> 0x7f934701ae48, 0x7f93468b01b8, undef:i64, <stdin>:5:8 @[ <stdin>:3:1 ]
                0x7f93468b01b8: i64 = add nuw 0x7f93468afc08, Constant:i64<8>, <stdin>:5:8 @[ <stdin>:3:1 ]
                  0x7f93468afc08: i64,ch = CopyFromReg 0x7f934701ae48, Register:i64 %2

                  0x7f93468afee0: i64 = Constant<8>
                0x7f93468afda8: i64 = undef
          0x7f93468b3368: i8 = Constant<1>
      0x7f9346882940: i64 = Constant<10>
    0x7f93468afda8: i64 = undef
  0x7f93468828d8: i64 = add 0x7f93468b2ce8, Constant:i64<34>, <stdin>:5:8 @[ <stdin>:3:1 ]
    0x7f93468b2ce8: i64 = add 0x7f93468b29a8, 0x7f93468affb0, <stdin>:5:8 @[ <stdin>:3:1 ]
      0x7f93468b29a8: i64 = shl 0x7f93468b0768, Constant:i8<1>
        0x7f93468b0768: i64 = add 0x7f93468b28d8, 0x7f93468b2870
          0x7f93468b28d8: i64 = add nuw nsw 0x7f93468b26d0, 0x7f93468b08a0
            0x7f93468b26d0: i64 = X86ISD::MUL_IMM 0x7f93468b07d0, Constant:i64<3>, <stdin>:5:8 @[ <stdin>:3:1 ]
              0x7f93468b07d0: i64,ch = load<(dereferenceable load (s32) from %ir.2, align 16), zext from i32> 0x7f934701ae48, 0x7f93468afc08, undef:i64, <stdin>:5:8 @[ <stdin>:3:1 ]
                0x7f93468afc08: i64,ch = CopyFromReg 0x7f934701ae48, Register:i64 %2
                  0x7f93468afba0: i64 = Register %2
                0x7f93468afda8: i64 = undef
              0x7f93468b0970: i64 = Constant<3>
            0x7f93468b08a0: i64 = shl 0x7f93468b0288, Constant:i8<1>, <stdin>:5:8 @[ <stdin>:3:1 ]
              0x7f93468b0288: i64 = X86ISD::MUL_IMM 0x7f93468b0018, Constant:i64<3>, <stdin>:5:8 @[ <stdin>:3:1 ]
                0x7f93468b0018: i64,ch = load<(dereferenceable load (s32) from %ir.2 + 4, basealign 16), zext from i32> 0x7f934701ae48, 0x7f93468b00e8, undef:i64, <stdin>:5:8 @[ <stdin>:3:1 ]
                  0x7f93468b00e8: i64 = add nuw 0x7f93468afc08, Constant:i64<4>, <stdin>:5:8 @[ <stdin>:3:1 ]


                  0x7f93468afda8: i64 = undef
                0x7f93468b0970: i64 = Constant<3>
              0x7f93468b3368: i8 = Constant<1>
          0x7f93468b2870: i64 = mul nuw nsw 0x7f93468b0150, Constant:i64<54>, <stdin>:5:8 @[ <stdin>:3:1 ]
            0x7f93468b0150: i64,ch = load<(dereferenceable load (s16) from %ir.2 + 8, align 8, basealign 16), zext from i16> 0x7f934701ae48, 0x7f93468b01b8, undef:i64, <stdin>:5:8 @[ <stdin>:3:1 ]
              0x7f93468b01b8: i64 = add nuw 0x7f93468afc08, Constant:i64<8>, <stdin>:5:8 @[ <stdin>:3:1 ]
                0x7f93468afc08: i64,ch = CopyFromReg 0x7f934701ae48, Register:i64 %2
                  0x7f93468afba0: i64 = Register %2
                0x7f93468afee0: i64 = Constant<8>
              0x7f93468afda8: i64 = undef
            0x7f93468b2808: i64 = Constant<54>
        0x7f93468b3368: i8 = Constant<1>
      0x7f93468affb0: i64,ch = load<(load (s64) from %ir.7)> 0x7f934701ae48, 0x7f93468aff48, undef:i64, <stdin>:5:8 @[ <stdin>:3:1 ]
        0x7f93468aff48: i64 = add 0x7f93468afe10, Constant:i64<8>, <stdin>:5:8 @[ <stdin>:3:1 ]
          0x7f93468afe10: i64,ch = load<(dereferenceable load (s64) from %ir..elt19, align 16)> 0x7f934701ae48, 0x7f93468afcd8, undef:i64, <stdin>:3:1
            0x7f93468afcd8: i64 = add nuw 0x7f93468afb38, Constant:i64<32>, <stdin>:3:1
              0x7f93468afb38: i64,ch = CopyFromReg 0x7f934701ae48, Register:i64 %1
                0x7f93468afad0: i64 = Register %1
              0x7f93468afc70: i64 = Constant<32>
            0x7f93468afda8: i64 = undef
          0x7f93468afee0: i64 = Constant<8>
        0x7f93468afda8: i64 = undef
    0x7f9346882668: i64 = Constant<34>
  0x7f93468afda8: i64 = undef
In function: main_dispatch_0
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /Users/phawkins/.pyenv/versions/3.10.0/envs/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/phawkins/.pyenv/versions/3.10.0/envs/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
1.	Running pass 'Function Pass Manager' on module '<stdin>_linked_llvm'.
2.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@main_dispatch_0'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libIREECompilerAggregateCAPI.dylib 0x000000011e7aab67 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 39
1  libIREECompilerAggregateCAPI.dylib 0x000000011e7a9a48 llvm::sys::RunSignalHandlers() + 248
2  libIREECompilerAggregateCAPI.dylib 0x000000011e7ab1c0 llvm::sys::PrintStackTraceOnErrorSignal(llvm::StringRef, bool) + 720
3  libsystem_platform.dylib           0x00007ff80c680dfd _sigtramp + 29
4  libsystem_platform.dylib           0x00007ff7b16d1780 _sigtramp + 18446744072183155104
5  libsystem_c.dylib                  0x00007ff80c5b6d24 abort + 123
6  libIREECompilerAggregateCAPI.dylib 0x000000011e6dd41d llvm::report_fatal_error(llvm::Twine const&, bool) + 461
7  libIREECompilerAggregateCAPI.dylib 0x00000001210cd4ab llvm::SelectionDAGISel::CannotYetSelect(llvm::SDNode*) + 891
8  libIREECompilerAggregateCAPI.dylib 0x00000001210cc47d llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) + 17005
9  libIREECompilerAggregateCAPI.dylib 0x0000000120569c0a llvm::createX86ISelDag(llvm::X86TargetMachine&, llvm::CodeGenOpt::Level) + 55034
10 libIREECompilerAggregateCAPI.dylib 0x00000001210c3f0f llvm::SelectionDAGISel::DoInstructionSelection() + 383
11 libIREECompilerAggregateCAPI.dylib 0x00000001210c34d8 llvm::SelectionDAGISel::CodeGenAndEmitDAG() + 1304
12 libIREECompilerAggregateCAPI.dylib 0x00000001210c28f2 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) + 6098
13 libIREECompilerAggregateCAPI.dylib 0x00000001210c03f2 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) + 2466
14 libIREECompilerAggregateCAPI.dylib 0x000000012055c610 llvm::createX86ISelDag(llvm::X86TargetMachine&, llvm::CodeGenOpt::Level) + 256
15 libIREECompilerAggregateCAPI.dylib 0x00000001212cf125 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 277
16 libIREECompilerAggregateCAPI.dylib 0x00000001225d7beb llvm::FPPassManager::runOnFunction(llvm::Function&) + 907
17 libIREECompilerAggregateCAPI.dylib 0x00000001225dddbc llvm::FPPassManager::runOnModule(llvm::Module&) + 60
18 libIREECompilerAggregateCAPI.dylib 0x00000001225d8205 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 933
19 libIREECompilerAggregateCAPI.dylib 0x000000011fc43a7e mlir::iree_compiler::IREE::LinalgExt::registerBufferizableOpInterfaceExternalModels(mlir::DialectRegistry&) + 61838
20 libIREECompilerAggregateCAPI.dylib 0x000000011fc3c643 mlir::iree_compiler::IREE::LinalgExt::registerBufferizableOpInterfaceExternalModels(mlir::DialectRegistry&) + 32083
21 libIREECompilerAggregateCAPI.dylib 0x00000001200ab708 mlir::iree_compiler::IREE::LinalgExt::createTiledOpInterfaceTilingPass() + 245304
22 libIREECompilerAggregateCAPI.dylib 0x000000011e7e2ca6 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 966
23 libIREECompilerAggregateCAPI.dylib 0x000000011e7e3466 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 358
24 libIREECompilerAggregateCAPI.dylib 0x000000011e7e6f15 mlir::PassInstrumentor::runAfterAnalysis(llvm::StringRef, mlir::TypeID, mlir::Operation*) + 4421
25 libIREECompilerAggregateCAPI.dylib 0x00000001200ac492 mlir::iree_compiler::IREE::LinalgExt::createTiledOpInterfaceTilingPass() + 248770
26 libIREECompilerAggregateCAPI.dylib 0x000000011e7e2ca6 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 966
27 libIREECompilerAggregateCAPI.dylib 0x000000011e7e3466 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 358
28 libIREECompilerAggregateCAPI.dylib 0x000000011e7e7d6e mlir::PassInstrumentor::runAfterAnalysis(llvm::StringRef, mlir::TypeID, mlir::Operation*) + 8094
29 libIREECompilerAggregateCAPI.dylib 0x000000011e7e446b mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) + 1659
30 libIREECompilerAggregateCAPI.dylib 0x000000011e7e2cd7 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 1015
31 libIREECompilerAggregateCAPI.dylib 0x000000011e7e3466 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 358
32 libIREECompilerAggregateCAPI.dylib 0x000000011e7e4f46 mlir::PassManager::run(mlir::Operation*) + 486
33 libIREECompilerAggregateCAPI.dylib 0x000000011e34a9bb mlir::detail::walk(mlir::Operation*, llvm::function_ref<mlir::WalkResult (mlir::Operation*, mlir::WalkStage const&)>) + 2365451
34 libIREECompilerAggregateCAPI.dylib 0x000000011e3499f7 mlir::detail::walk(mlir::Operation*, llvm::function_ref<mlir::WalkResult (mlir::Operation*, mlir::WalkStage const&)>) + 2361415
35 dyld                               0x0000000111c8651e start + 462


Invoked with:
 iree-compile /Users/phawkins/.pyenv/versions/3.10.0/envs/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/phawkins/.pyenv/versions/3.10.0/envs/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
```

**Comment by alliemartens** [comment]
Assigning to @jpienaar @rsuderman to set priority and assignees.

**Comment by alliemartens** [comment]
@not-jenni Can you help review and prioritize this on frontend rotation this week?

**Comment by jpienaar** [comment]
This currently fails at head with

```
lld: error: undefined symbol: __truncsfbf2
>>> referenced by 7612.mlir:4 (/tmp/7612.mlir:4)
>>>               /tmp/7612_linked_llvm-63d46b.o:(main_dispatch_1)
>>> referenced by 7612.mlir:4 (/tmp/7612.mlir:4)
>>>               /tmp/7612_linked_llvm-63d46b.o:(main_dispatch_1)
>>> referenced by 7612.mlir:4 (/tmp/7612.mlir:4)
>>>               /tmp/7612_linked_llvm-63d46b.o:(main_dispatch_1)
>>> referenced 12 more times
>>> did you mean: __truncsfhf2
>>> defined in: /tmp/7612_linked_llvm-63d46b.o
Linking failed; escaped command line returned exit code 256:
```

so we get post lowering from MHLO and compilation, but then these aren't in library linked in.

**Comment by MaheshRavishankar** [comment]
Damn! More library calls generated by LLVM. I'll fix it in a bit.

**Comment by allieculp** [comment]
@MaheshRavishankar Still open? Still P1?

**Comment by MaheshRavishankar** [comment]
I dont know. I am not working on it. I dont remember if I already fixed it... We can drop it down to P2 since its old.
