### ISSUE TITLE
Shape check error for convolution

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7613]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<3x2x9x10xf16>, %arg1: tensor<2x2x4x5xf16>) -> tensor<3x2x14x11xf16> {
    %0 = mhlo.convolution(%arg0, %arg1) dim_numbers = [b, f, 0, 1]x[o, i, 0, 1]->[b, f, 0, 1], window = {stride = [1, 1], pad = [[0, 0], [0, 0]], lhs_dilate = [2, 2], rhs_dilate = [1, 2], reverse = [0, 0]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<3x2x9x10xf16>, tensor<2x2x4x5xf16>) -> tensor<3x2x14x11xf16>
    return %0 : tensor<3x2x14x11xf16>
  }
}"""
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:4:10: error: 'linalg.conv_2d_nhwc_hwcf' op inferred input/output operand #0 has shape's dimension #1 to be greater than or equal to 17, but found 9
    %0 = mhlo.convolution(%arg0, %arg1) dim_numbers = [b, f, 0, 1]x[o, i, 0, 1]->[b, f, 0, 1], window = {stride = [1, 1], pad = [[0, 0], [0, 0]], lhs_dilate = [2, 2], rhs_dilate = [1, 2], reverse = [0, 0]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<3x2x9x10xf16>, tensor<2x2x4x5xf16>) -> tensor<3x2x14x11xf16>
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<3x2x9x10xf16>, %arg1: tensor<2x2x4x5xf16>) -> tensor<3x2x14x11xf16> {
  ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

The convolution passed the mhlo verifier, so presumably this is a problem in IREE's lowering.

**Comment by hanhanW** [comment]
I think mhlo.convolution does not have a verifier, so it still could be an invalid op. We should verify that

1. The input convolution op is valid.
2. The output IR of IREE MHLOToMHLOPreprocessing is valid.
3. If there are issues in convolution -> linalg.conv_2d_nhwc_hwcf.

Before just looking into (3), I think we should go with (1), then (2).

**Comment by rsuderman** [comment]
Reasonably certain that the issue is it contains left and right dilation. I seriously doubt any of our operations are designed to deal with that. Mentally putting this as lower priority as dilation is frustrating to work with.

**Comment by jpienaar** [comment]
Working at head.

Updated input

```mlir
module  {
  func.func @main(%arg0: tensor<3x2x9x10xf16>, %arg1: tensor<2x2x4x5xf16>) -> tensor<3x2x14x11xf16> {
    %0 = mhlo.convolution(%arg0, %arg1) dim_numbers = [b, f, 0, 1]x[o, i, 0, 1]->[b, f, 0, 1], window = {stride = [1, 1], pad = [[0, 0], [0, 0]], lhs_dilate = [2, 2], rhs_dilate = [1, 2], reverse = [0, 0]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64, precision_config = [#mhlo<"precision DEFAULT">, #mhlo<"precision DEFAULT">]} : (tensor<3x2x9x10xf16>, tensor<2x2x4x5xf16>) -> tensor<3x2x14x11xf16>
    return %0 : tensor<3x2x14x11xf16>
  }
}
```
