### ISSUE TITLE
Failed to legalize `math.atan2`

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7615]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<1x4xf16>) -> tensor<1x4xf16> {
    %0 = call @main_0(%arg0) : (tensor<1x4xf16>) -> tensor<1x4xf16>
    return %0 : tensor<1x4xf16>
  }
  func private @main_0(%arg0: tensor<1x4xf16>) -> tensor<1x4xf16> {
    %0 = mhlo.constant dense<false> : tensor<i1>
    %1 = mhlo.constant dense<false> : tensor<i1>
    %2 = mhlo.constant dense<-1.000000e+00> : tensor<f16>
    %3 = "mhlo.broadcast_in_dim"(%2) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<f16>) -> tensor<1x4xf16>
    %4 = "mhlo.compare"(%arg0, %3) {comparison_direction = "NE"} : (tensor<1x4xf16>, tensor<1x4xf16>) -> tensor<1x4xi1>
    %5 = mhlo.constant dense<2.000000e+00> : tensor<f16>
    %6 = "mhlo.broadcast_in_dim"(%5) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<f16>) -> tensor<1x4xf16>
    %7 = mhlo.constant dense<1.000000e+00> : tensor<f16>
    %8 = "mhlo.broadcast_in_dim"(%7) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<f16>) -> tensor<1x4xf16>
    %9 = mhlo.multiply %arg0, %arg0 : tensor<1x4xf16>
    %10 = mhlo.subtract %8, %9 : tensor<1x4xf16>
    %11 = "mhlo.sqrt"(%10) : (tensor<1x4xf16>) -> tensor<1x4xf16>
    %12 = mhlo.constant dense<1.000000e+00> : tensor<f16>
    %13 = "mhlo.broadcast_in_dim"(%12) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<f16>) -> tensor<1x4xf16>
    %14 = mhlo.add %13, %arg0 : tensor<1x4xf16>
    %15 = mhlo.atan2 %11, %14 : tensor<1x4xf16>
    %16 = mhlo.multiply %6, %15 : tensor<1x4xf16>
    %17 = mhlo.constant dense<3.140630e+00> : tensor<f16>
    %18 = "mhlo.broadcast_in_dim"(%17) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<f16>) -> tensor<1x4xf16>
    %19 = "mhlo.select"(%4, %16, %18) : (tensor<1x4xi1>, tensor<1x4xf16>, tensor<1x4xf16>) -> tensor<1x4xf16>
    return %19 : tensor<1x4xf16>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 35, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:23:11: error: failed to legalize operation 'math.atan2' that was explicitly marked illegal
    %15 = mhlo.atan2 %11, %14 : tensor<1x4xf16>
          ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<1x4xf16>) -> tensor<1x4xf16> {
  ^
<stdin>:27:11: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"llvm", "embedded-elf-x86_64", {data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
    %19 = "mhlo.select"(%4, %16, %18) : (tensor<1x4xi1>, tensor<1x4xf16>, tensor<1x4xf16>) -> tensor<1x4xf16>
          ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<1x4xf16>) -> tensor<1x4xf16> {
  ^
<stdin>:27:11: error: failed to serialize executables
    %19 = "mhlo.select"(%4, %16, %18) : (tensor<1x4xi1>, tensor<1x4xf16>, tensor<1x4xf16>) -> tensor<1x4xf16>
          ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<1x4xf16>) -> tensor<1x4xf16> {
  ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by hanhanW** [comment]
I guess this not only happens on CPU backend, but also CUDA backend. There are no atan2 in LLVM intrinsics, so we will have to expand the op before lowering it into LLVM dialect.

E.g.,

https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Math/Transforms/ExpandTanh.cpp

**Comment by rsuderman** [comment]
Looks like we will need to add an approximation for atan2 to the list of polynomial approximations:

https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Math/Transforms/PolynomialApproximation.cpp

**Comment by rsuderman** [comment]
Solution was committed. Waiting LLVM to roll and we can validate.

**Comment by rsuderman** [comment]
Failure is now related to being f16. Likely we will want to add casts around polynomial approximations.

**Comment by jpienaar** [comment]
Expansion for it to f16 landed upstream, but will require a bump still

**Comment by jpienaar** [comment]
Version has been bumped, at head

```
iree-translate --iree-input-type=mhlo /tmp/above_ir.mlir --iree-mlir-to-vm-c-module --iree-hal-target-backends=cpu
```

is working.
