### ISSUE TITLE
Failed to legalize operation `builtin.unrealized_conversion_cast`

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7616]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<3x1xui32>, %arg1: tensor<1x4xui32>) -> tensor<3x4xi1> {
    %0 = "mhlo.broadcast_in_dim"(%arg0) {broadcast_dimensions = dense<[0, 1]> : tensor<2xi64>} : (tensor<3x1xui32>) -> tensor<3x4xui32>
    %1 = "mhlo.broadcast_in_dim"(%arg1) {broadcast_dimensions = dense<[0, 1]> : tensor<2xi64>} : (tensor<1x4xui32>) -> tensor<3x4xui32>
    %2 = "mhlo.compare"(%0, %1) {compare_type = "UNSIGNED", comparison_direction = "EQ"} : (tensor<3x4xui32>, tensor<3x4xui32>) -> tensor<3x4xi1>
    return %2 : tensor<3x4xi1>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 14, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:4:10: error: failed to legalize operation 'builtin.unrealized_conversion_cast' that was explicitly marked illegal
    %0 = "mhlo.broadcast_in_dim"(%arg0) {broadcast_dimensions = dense<[0, 1]> : tensor<2xi64>} : (tensor<3x1xui32>) -> tensor<3x4xui32>
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<3x1xui32>, %arg1: tensor<1x4xui32>) -> tensor<3x4xi1> {
  ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by stellaraccident** [comment]
I expect this is fixed by https://github.com/google/iree/pull/7711 . Will verify once it lands.

**Comment by rsuderman** [comment]
Validated that this is fixed at head.
