### ISSUE TITLE
LLVM instruction selection failure for bf16 comparison

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7617]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<2x3x4xbf16>, %arg1: tensor<2x1x4xbf16>) -> tensor<2x3x4xi1> {
    %0 = "mhlo.broadcast_in_dim"(%arg1) {broadcast_dimensions = dense<[0, 1, 2]> : tensor<3xi64>} : (tensor<2x1x4xbf16>) -> tensor<2x3x4xbf16>
    %1 = "mhlo.compare"(%arg0, %0) {compare_type = "FLOAT", comparison_direction = "LE"} : (tensor<2x3x4xbf16>, tensor<2x3x4xbf16>) -> tensor<2x3x4xi1>
    return %1 : tensor<2x3x4xi1>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 13, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
LLVM ERROR: Cannot select: 0x7f6d080ec388: i8 = setcc 0x7f6d080e5ba8, 0x7f6d080ecb40, setole:ch, <stdin>:5:10 @[ <stdin>:3:3 ]
  0x7f6d080e5ba8: bf16,ch = load<(load (s16) from %ir.scevgep74)> 0x7f6d0808e1c8, 0x7f6d080e5388, undef:i64, <stdin>:5:10 @[ <stdin>:3:3 ]
    0x7f6d080e5388: i64 = add 0x7f6d080e5a70, 0x7f6d080e5730, <stdin>:5:10 @[ <stdin>:3:3 ]
      0x7f6d080e5a70: i64,ch = CopyFromReg 0x7f6d0808e1c8, Register:i64 %27, <stdin>:5:10 @[ <stdin>:3:3 ]
        0x7f6d080ebe40: i64 = Register %27
      0x7f6d080e5730: i64 = shl 0x7f6d080ec730, Constant:i8<1>, <stdin>:5:10 @[ <stdin>:3:3 ]
        0x7f6d080ec730: i64,ch = CopyFromReg 0x7f6d0808e1c8, Register:i64 %36, <stdin>:5:10 @[ <stdin>:3:3 ]
          0x7f6d080e5320: i64 = Register %36
        0x7f6d080e5c78: i8 = Constant<1>
    0x7f6d080ecba8: i64 = undef
  0x7f6d080ecb40: bf16,ch = load<(load (s16) from %ir.scevgep55)> 0x7f6d0808e1c8, 0x7f6d080ec3f0, undef:i64, <stdin>:5:10 @[ <stdin>:3:3 ]
    0x7f6d080ec3f0: i64 = add 0x7f6d080ec180, 0x7f6d080e5730, <stdin>:5:10 @[ <stdin>:3:3 ]
      0x7f6d080ec180: i64,ch = CopyFromReg 0x7f6d0808e1c8, Register:i64 %29, <stdin>:5:10 @[ <stdin>:3:3 ]
        0x7f6d080e5660: i64 = Register %29
      0x7f6d080e5730: i64 = shl 0x7f6d080ec730, Constant:i8<1>, <stdin>:5:10 @[ <stdin>:3:3 ]
        0x7f6d080ec730: i64,ch = CopyFromReg 0x7f6d0808e1c8, Register:i64 %36, <stdin>:5:10 @[ <stdin>:3:3 ]
          0x7f6d080e5320: i64 = Register %36
        0x7f6d080e5c78: i8 = Constant<1>
    0x7f6d080ecba8: i64 = undef
In function: main_dispatch_0
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Running pass 'Function Pass Manager' on module 'main_dispatch_0'.
1.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@main_dispatch_0'
 #0 0x00007f6d1aa7c450 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd23450)
 #1 0x00007f6d1aa7a20e (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd2120e)
 #2 0x00007f6d19bafef0 (/lib/x86_64-linux-gnu/libc.so.6+0x3cef0)
 #3 0x00007f6d19bafe71 raise ./signal/../sysdeps/unix/sysv/linux/raise.c:50:1
 #4 0x00007f6d19b99536 abort ./stdlib/abort.c:81:7
 #5 0x00007f6d1aa091d6 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xcb01d6)
 #6 0x00007f6d1cfb51ec (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x325c1ec)
 #7 0x00007f6d1cfba982 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x3261982)
 #8 0x00007f6d1c133b0f (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x23dab0f)
 #9 0x00007f6d1cfb4208 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x325b208)
#10 0x00007f6d1cfbeffc (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x3265ffc)
#11 0x00007f6d1cfc19fe (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x32689fe)
#12 0x00007f6d1cfc4836 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x326b836)
#13 0x00007f6d1c13d6b1 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x23e46b1)
#14 0x00007f6d1d2817c7 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x35287c7)
#15 0x00007f6d1e80b5d0 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x4ab25d0)
#16 0x00007f6d1e80cc71 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x4ab3c71)
#17 0x00007f6d1e80a930 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x4ab1930)
#18 0x00007f6d1b54cc98 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x17f3c98)
#19 0x00007f6d1b5462e3 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x17ed2e3)
#20 0x00007f6d1b75717b (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x19fe17b)
#21 0x00007f6d1aacb10d (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd7210d)
#22 0x00007f6d1aacb250 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd72250)
#23 0x00007f6d1aacb584 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd72584)
#24 0x00007f6d1b758419 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x19ff419)
#25 0x00007f6d1aacb10d (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd7210d)
#26 0x00007f6d1aacb250 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd72250)
#27 0x00007f6d1aacc4f2 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd734f2)
#28 0x00007f6d1aa2f142 std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::function<void ()>, std::allocator<int>, void ()>::_M_run()::'lambda'(), void> >::_M_invoke(std::_Any_data const&) (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xcd6142)
#29 0x00007f6d1a5fdebb (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x8a4ebb)
#30 0x00007f6d19b62a7f __pthread_once_slow ./nptl/pthread_once.c:118:7
#31 0x00007f6d1aa2f9a6 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xcd69a6)
#32 0x00007f6d19b5aeae start_thread ./nptl/pthread_create.c:464:7
#33 0x00007f6d19c70a5f clone ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97:0


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

Most likely this means that IREE needs to legalize bf16 away because LLVM won't do anything useful with it.

**Comment by jpienaar** [comment]
This is working at head. (`iree-compile /tmp/t1.mlir  --iree-input-type=xla --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --mlir-print-debuginfo --mlir-print-op-on-diagnostic=true -o /dev/null` passing)
