### ISSUE TITLE
Missing legalization for `mhlo.reduce_window` (?)

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7619]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<4x6xf32>) -> tensor<4x7xf32> {
    %0 = mhlo.constant dense<0.000000e+00> : tensor<f32>
    %1 = "mhlo.broadcast"(%0) {broadcast_sizes = dense<> : tensor<0xi64>} : (tensor<f32>) -> tensor<f32>
    %2 = "mhlo.reduce_window"(%arg0, %1) ( {
    ^bb0(%arg1: tensor<f32>, %arg2: tensor<f32>):  // no predecessors
      %3 = mhlo.add %arg1, %arg2 : tensor<f32>
      "mhlo.return"(%3) : (tensor<f32>) -> ()
    }) {base_dilations = dense<1> : tensor<2xi64>, padding = dense<[[0, 3], [1, 2]]> : tensor<2x2xi64>, window_dilations = dense<[1, 2]> : tensor<2xi64>, window_dimensions = dense<[1, 2]> : tensor<2xi64>, window_strides = dense<[2, 1]> : tensor<2xi64>} : (tensor<4x6xf32>, tensor<f32>) -> tensor<4x7xf32>
    return %2 : tensor<4x7xf32>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 18, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:6:10: error: failed to legalize operation 'mhlo.reduce_window' that was explicitly marked illegal
    %2 = "mhlo.reduce_window"(%arg0, %1) ( {
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<4x6xf32>) -> tensor<4x7xf32> {
  ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by hanhanW** [comment]
I'm the author of lowering mhlo.reduce_window to Linalg on tensors. Only 2D/3D pooling based reduce_window ops are supported, IIRC. IMO, we can lower it to a generic op for other cases.

**Comment by hawkinsp** [comment]
Arbitrary numbers of dimensions really should be supported (for all ops).

**Comment by hanhanW** [comment]
I agree that they should be supported. :)

It was not on our priorities and reduction in Linalg on tensors was not clear enough when developing the op lowering. Now I'm confident that it can be supported in linalg.generic op form.

**Comment by hanhanW** [comment]
https://github.com/google/iree/issues/7885 has more context about how we can lower it.

**Comment by rsuderman** [comment]
Fixed in a previous mhlo-to-linalg [commit](https://github.com/tensorflow/tensorflow/commit/9050a120e161936a73e953df6619b489f2466841#diff-5f608b167d4dc35b869c40a5dafb3457312227aa75a1b1525fd9831ab831d58a)
