### ISSUE TITLE
"Failed to legalize unresolved materialization from 'ui8' to 'i8' that remained live after conversion"

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7620]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<5x3xui8>, %arg1: tensor<5x3xf32>) -> (tensor<5x3xui8>, tensor<5x3xf32>) {
    %0:2 = "mhlo.sort"(%arg0, %arg1) ( {
    ^bb0(%arg2: tensor<ui8>, %arg3: tensor<ui8>, %arg4: tensor<f32>, %arg5: tensor<f32>):  // no predecessors
      %1 = "mhlo.compare"(%arg2, %arg3) {compare_type = "UNSIGNED", comparison_direction = "LT"} : (tensor<ui8>, tensor<ui8>) -> tensor<i1>
      "mhlo.return"(%1) : (tensor<i1>) -> ()
    }) {dimension = 1 : i64, is_stable = false} : (tensor<5x3xui8>, tensor<5x3xf32>) -> (tensor<5x3xui8>, tensor<5x3xf32>)
    return %0#0, %0#1 : tensor<5x3xui8>, tensor<5x3xf32>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 16, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:6:12: error: failed to legalize unresolved materialization from 'ui8' to 'i8' that remained live after conversion
      %1 = "mhlo.compare"(%arg2, %arg3) {compare_type = "UNSIGNED", comparison_direction = "LT"} : (tensor<ui8>, tensor<ui8>) -> tensor<i1>
           ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<5x3xui8>, %arg1: tensor<5x3xf32>) -> (tensor<5x3xui8>, tensor<5x3xf32>) {
  ^
<stdin>:6:12: note: see existing live user here: %8 = arith.cmpi ult, %7, %6 : i8 loc(callsite("<stdin>":6:12 at "<stdin>":3:3))
      %1 = "mhlo.compare"(%arg2, %arg3) {compare_type = "UNSIGNED", comparison_direction = "LT"} : (tensor<ui8>, tensor<ui8>) -> tensor<i1>
           ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by stellaraccident** [comment]
I expect this will be fixed by https://github.com/google/iree/pull/7711. Will verify and triage further when it lands.
