### ISSUE TITLE
Crash in ireec for complex convolution

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7621]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<2x2x9x10xcomplex<f32>>, %arg1: tensor<2x2x4x5xcomplex<f32>>) -> tensor<2x2x6x6xcomplex<f32>> {
    %0 = mhlo.convolution(%arg0, %arg1) dim_numbers = [b, f, 0, 1]x[o, i, 0, 1]->[b, f, 0, 1], window = {stride = [1, 1], pad = [[0, 0], [0, 0]], lhs_dilate = [1, 1], rhs_dilate = [1, 1], reverse = [0, 0]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<2x2x9x10xcomplex<f32>>, tensor<2x2x4x5xcomplex<f32>>) -> tensor<2x2x6x6xcomplex<f32>>
    return %0 : tensor<2x2x6x6xcomplex<f32>>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 12, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
 #0 0x00007f9fb8c17450 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd23450)
 #1 0x00007f9fb8c1520e (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd2120e)
 #2 0x00007f9fb7d4aef0 (/lib/x86_64-linux-gnu/libc.so.6+0x3cef0)
 #3 0x00007f9fb8620293 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x72c293)
 #4 0x00007f9fb8cee708 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xdfa708)
 #5 0x00007f9fb95331d1 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x163f1d1)
 #6 0x00007f9fb9d211d3 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x1e2d1d3)
 #7 0x00007f9fb9ccbd03 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x1dd7d03)
 #8 0x00007f9fbc80f8e9 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x491b8e9)
 #9 0x00007f9fbca78760 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x4b84760)
#10 0x00007f9fbc81a6c4 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x49266c4)
#11 0x00007f9fbc81bc6b (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x4927c6b)
#12 0x00007f9fbc81d7d9 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x49297d9)
#13 0x00007f9fb9acb64d (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x1bd764d)
#14 0x00007f9fb8c6610d (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd7210d)
#15 0x00007f9fb8c66250 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd72250)
#16 0x00007f9fb8c64d60 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd70d60)
#17 0x00007f9fb8c65e54 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd71e54)
#18 0x00007f9fb8c66250 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd72250)
#19 0x00007f9fb8c67293 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd73293)
#20 0x00007f9fb8792ec2 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x89eec2)
#21 0x00007f9fb8793607 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x89f607)
#22 0x00007f9fbc27b00b (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x438700b)
#23 0x00007f9fb8796060 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x8a2060)
#24 0x00007f9fb7d35e4a __libc_start_main ./csu/../csu/libc-start.c:314:16
#25 0x000000000040108e _init (/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec+0x40108e)


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by hawkinsp** [comment]
This is probably an instance of a similar bug:
```
module  {
  func @main(%arg0: tensor<4x3xcomplex<f32>>, %arg1: tensor<3x6xcomplex<f32>>) -> tensor<4x6xcomplex<f32>> {
    %0 = "mhlo.dot_general"(%arg0, %arg1) {dot_dimension_numbers = #mhlo.dot<lhs_contracting_dimensions = [1], rhs_contracting_dimensions = [0]>, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<4x3xcomplex<f32>>, tensor<3x6xcomplex<f32>>) -> tensor<4x6xcomplex<f32>>
    return %0 : tensor<4x6xcomplex<f32>>
  }
}
```

**Comment by jpienaar** [comment]
With input now

```mlir
module  {
  func.func @main(%arg0: tensor<2x2x9x10xcomplex<f32>>, %arg1: tensor<2x2x4x5xcomplex<f32>>) -> tensor<2x2x6x6xcomplex<f32>> {
    %0 = mhlo.convolution(%arg0, %arg1) dim_numbers = [b, f, 0, 1]x[o, i, 0, 1]->[b, f, 0, 1], window = {stride = [1, 1], pad = [[0, 0], [0, 0]], lhs_dilate = [1, 1], rhs_dilate = [1, 1], reverse = [0, 0]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64, precision_config = [#mhlo<"precision DEFAULT">, #mhlo<"precision DEFAULT">]} : (tensor<2x2x9x10xcomplex<f32>>, tensor<2x2x4x5xcomplex<f32>>) -> tensor<2x2x6x6xcomplex<f32>>
    return %0 : tensor<2x2x6x6xcomplex<f32>>
  }
}
```

iree-compile now fails with

> invalid tensor element type: 'complex<f32>'

in `ConvertToStream`.

**Comment by jpienaar** [comment]
After the above change this fails in stream-conversion

```mlir
// configuration: -pass-pipeline='iree-stream-conversion' -mlir-disable-threading -verify-each
module {
  func.func @main(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub} {
    %0 = hal.tensor.import %arg0 : !hal.buffer_view -> tensor<4x3xcomplex<f32>>
    %1 = hal.tensor.import %arg1 : !hal.buffer_view -> tensor<3x6xcomplex<f32>>
    %2 = call @_main(%0, %1) : (tensor<4x3xcomplex<f32>>, tensor<3x6xcomplex<f32>>) -> tensor<4x6xcomplex<f32>>
    %3 = hal.tensor.export %2 : tensor<4x6xcomplex<f32>> -> !hal.buffer_view
    return %3 : !hal.buffer_view
  }
  flow.executable private @_main_dispatch_0 {
    flow.executable.export public @_main_dispatch_0
    builtin.module {
      func.func @_main_dispatch_0(%arg0: complex<f32>, %arg1: !flow.dispatch.tensor<readonly:4x3xcomplex<f32>>, %arg2: !flow.dispatch.tensor<readonly:3x6xcomplex<f32>>, %arg3: !flow.dispatch.tensor<writeonly:4x6xcomplex<f32>>) {
        %0 = flow.dispatch.tensor.load %arg1, offsets = [0, 0], sizes = [4, 3], strides = [1, 1] : !flow.dispatch.tensor<readonly:4x3xcomplex<f32>> -> tensor<4x3xcomplex<f32>>
        %1 = flow.dispatch.tensor.load %arg2, offsets = [0, 0], sizes = [3, 6], strides = [1, 1] : !flow.dispatch.tensor<readonly:3x6xcomplex<f32>> -> tensor<3x6xcomplex<f32>>
        %2 = linalg.init_tensor [4, 6] : tensor<4x6xcomplex<f32>>
        %3 = linalg.fill ins(%arg0 : complex<f32>) outs(%2 : tensor<4x6xcomplex<f32>>) -> tensor<4x6xcomplex<f32>>
        %4 = linalg.matmul ins(%0, %1 : tensor<4x3xcomplex<f32>>, tensor<3x6xcomplex<f32>>) outs(%3 : tensor<4x6xcomplex<f32>>) -> tensor<4x6xcomplex<f32>>
        flow.dispatch.tensor.store %4, %arg3, offsets = [0, 0], sizes = [4, 6], strides = [1, 1] : tensor<4x6xcomplex<f32>> -> !flow.dispatch.tensor<writeonly:4x6xcomplex<f32>>
        return
      }
    }
  }
  func.func private @_main(%arg0: tensor<4x3xcomplex<f32>>, %arg1: tensor<3x6xcomplex<f32>>) -> tensor<4x6xcomplex<f32>> {
    %c4 = arith.constant 4 : index
    %c6 = arith.constant 6 : index
    %c1 = arith.constant 1 : index
    %cst = complex.constant [0.000000e+00 : f32, 0.000000e+00 : f32] : complex<f32>
    %0 = flow.dispatch @_main_dispatch_0::@_main_dispatch_0[%c4, %c6, %c1](%cst, %arg0, %arg1) : (complex<f32>, tensor<4x3xcomplex<f32>>, tensor<3x6xcomplex<f32>>) -> tensor<4x6xcomplex<f32>>
    return %0 : tensor<4x6xcomplex<f32>>
  }
}
```

**Comment by benvanik** [comment]
complex types should be removed before entering the stream dialect or removed by the stream dialect immediately in buildStreamTensorPassPipeline before going to conversion. that includes scalars: those will need to be split into component parts (so a util.global of a complex should become two util.globals, all args/results should be expanded, etc). I thought we had a pass that did that awhile ago? @rsuderman

**Comment by benvanik** [comment]
#9626 adds some of the plumbing for buffer views with complex types across the ABI. There's still some work required to lower complex dialect ops and such to flow/stream but I think if there's interest in doing this kind of thing we'll need to gather more samples/requirements.
