### ISSUE TITLE
Crash in ireec for bool `mhlo.dot_general`

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7622]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<3x3x2xi1>, %arg1: tensor<2x3x4xi1>) -> tensor<3x3x4xi1> {
    %0 = "mhlo.dot_general"(%arg0, %arg1) {dot_dimension_numbers = #mhlo.dot<lhs_batching_dimensions = [0], rhs_batching_dimensions = [1], lhs_contracting_dimensions = [2], rhs_contracting_dimensions = [0]>, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<3x3x2xi1>, tensor<2x3x4xi1>) -> tensor<3x3x4xi1>
    return %0 : tensor<3x3x4xi1>
  }
}"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
 #0 0x00007f501f005450 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd23450)
 #1 0x00007f501f00320e (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd2120e)
 #2 0x00007f501e138ef0 (/lib/x86_64-linux-gnu/libc.so.6+0x3cef0)
 #3 0x00007f501ff78ec6 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x1c96ec6)
 #4 0x00007f501ff7b0aa (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x1c990aa)
 #5 0x00007f501ff61432 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x1c7f432)
 #6 0x00007f501f05410d (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd7210d)
 #7 0x00007f501f054250 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd72250)
 #8 0x00007f501f054584 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd72584)
 #9 0x00007f501fce32a3 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x1a012a3)
#10 0x00007f501f05410d (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd7210d)
#11 0x00007f501f054250 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd72250)
#12 0x00007f501f052d60 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd70d60)
#13 0x00007f501f053e54 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd71e54)
#14 0x00007f501f054250 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd72250)
#15 0x00007f501f054584 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd72584)
#16 0x00007f501fce44c1 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x1a024c1)
#17 0x00007f501f05410d (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd7210d)
#18 0x00007f501f054250 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd72250)
#19 0x00007f501f0554f2 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xd734f2)
#20 0x00007f501efb8142 std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::function<void ()>, std::allocator<int>, void ()>::_M_run()::'lambda'(), void> >::_M_invoke(std::_Any_data const&) (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xcd6142)
#21 0x00007f501eb86ebb (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0x8a4ebb)
#22 0x00007f501e0eba7f __pthread_once_slow ./nptl/pthread_once.c:118:7
#23 0x00007f501efb89a6 (/usr/local/google/home/phawkins/.pyenv/versions/3.7.3/envs/py373a/lib/python3.7/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.so+0xcd69a6)
#24 0x00007f501e0e3eae start_thread ./nptl/pthread_create.c:464:7
#25 0x00007f501e1f9a5f clone ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97:0


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by rsuderman** [comment]
Verified this now works at head.
