### ISSUE TITLE
Failed to legalize `mhlo.convolution` for a 0D convolution

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7624]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<3x2xf32>, %arg1: tensor<2x3xf32>) -> tensor<3x3xf32> {
    %0 = mhlo.convolution(%arg0, %arg1) dim_numbers = [b, f]x[i, o]->[b, f], window = {stride = [], pad = [], lhs_dilate = [], rhs_dilate = [], reverse = []} {batch_group_count = 1 : i64, feature_group_count = 1 : i64, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<3x2xf32>, tensor<2x3xf32>) -> tensor<3x3xf32>
    return %0 : tensor<3x3xf32>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 12, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:4:10: error: failed to legalize operation 'mhlo.convolution' that was explicitly marked illegal
    %0 = mhlo.convolution(%arg0, %arg1) dim_numbers = [b, f]x[i, o]->[b, f], window = {stride = [], pad = [], lhs_dilate = [], rhs_dilate = [], reverse = []} {batch_group_count = 1 : i64, feature_group_count = 1 : i64, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<3x2xf32>, tensor<2x3xf32>) -> tensor<3x3xf32>
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<3x2xf32>, %arg1: tensor<2x3xf32>) -> tensor<3x3xf32> {
  ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

A 0D convolution is perfectly legal, but the usual way to spell it is `mhlo.dot_general`.

**Comment by rsuderman** [comment]
Now compiles at HEAD
