### ISSUE TITLE
Missing legalization for `mhlo.popcnt`

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7625]
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<2x1x4xui32>) -> tensor<2x1x4xui32> {
    %0 = "mhlo.popcnt"(%arg0) : (tensor<2x1x4xui32>) -> tensor<2x1x4xui32>
    return %0 : tensor<2x1x4xui32>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 12, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:4:10: error: failed to legalize operation 'mhlo.popcnt' that was explicitly marked illegal
    %0 = "mhlo.popcnt"(%arg0) : (tensor<2x1x4xui32>) -> tensor<2x1x4xui32>
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<2x1x4xui32>) -> tensor<2x1x4xui32> {
  ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by hawkinsp** [comment]
It's possible this is a close cousin, since `mhlo.count_leading_zeros` is in the same category of operators as `mhlo.popcnt`:
```
module  {
  func @main(%arg0: tensor<3x1xi8>) -> tensor<3x1xi8> {
    %0 = "mhlo.count_leading_zeros"(%arg0) : (tensor<3x1xi8>) -> tensor<3x1xi8>
    return %0 : tensor<3x1xi8>
  }
}
```

**Comment by rsuderman** [comment]
Fixed in https://github.com/tensorflow/tensorflow/commit/eb27c380f3f4dfb456727fec79ae954267b5ad1d
