### ISSUE TITLE
"'arith.constant' op integer return type must be signless" for uint8 `mhlo.dot_general`

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7627]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<5x3x2xui8>, %arg1: tensor<3x5x2x4xui8>) -> tensor<3x3x4xui8> {
    %0 = "mhlo.dot_general"(%arg0, %arg1) {dot_dimension_numbers = #mhlo.dot<lhs_contracting_dimensions = [0, 2], rhs_contracting_dimensions = [1, 2]>, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<5x3x2xui8>, tensor<3x5x2x4xui8>) -> tensor<3x3x4xui8>
    return %0 : tensor<3x3x4xui8>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 12, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<unknown>:0: warning: could not cast operand of type 'i8' to 'ui8'
<unknown>:0: warning: could not cast operand of type 'i8' to 'ui8'
<stdin>:4:10: error: 'arith.constant' op integer return type must be signless
    %0 = "mhlo.dot_general"(%arg0, %arg1) {dot_dimension_numbers = #mhlo.dot<lhs_contracting_dimensions = [0, 2], rhs_contracting_dimensions = [1, 2]>, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<5x3x2xui8>, tensor<3x5x2x4xui8>) -> tensor<3x3x4xui8>
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<5x3x2xui8>, %arg1: tensor<3x5x2x4xui8>) -> tensor<3x3x4xui8> {
  ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by jpienaar** [comment]
`/tmp/github/iree-build/tools/iree-compile --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib  --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --mlir-pass-pipeline-crash-reproducer=/tmp/iree/core-reproducer.mlir /tmp/7627.mlir` working at head.
