### ISSUE TITLE
"'linalg.copy' op operand #1 must be strided memref of any type values" for degenerate `mhlo.dynamic-slice`

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7630]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<7x5x3xi8>, %arg1: tensor<i32>, %arg2: tensor<i32>, %arg3: tensor<i32>) -> tensor<2x0x1xi8> {
    %0 = "mhlo.dynamic-slice"(%arg0, %arg1, %arg2, %arg3) {slice_sizes = dense<[2, 0, 1]> : tensor<3xi64>} : (tensor<7x5x3xi8>, tensor<i32>, tensor<i32>, tensor<i32>) -> tensor<2x0x1xi8>
    return %0 : tensor<2x0x1xi8>
  }
}"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:4:10: error: 'linalg.copy' op operand #1 must be strided memref of any type values, but got 'memref<?x?xi8, affine_map<(d0, d1)[s0] -> (s0)>>'
    %0 = "mhlo.dynamic-slice"(%arg0, %arg1, %arg2, %arg3) {slice_sizes = dense<[2, 0, 1]> : tensor<3xi64>} : (tensor<7x5x3xi8>, tensor<i32>, tensor<i32>, tensor<i32>) -> tensor<2x0x1xi8>
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<7x5x3xi8>, %arg1: tensor<i32>, %arg2: tensor<i32>, %arg3: tensor<i32>) -> tensor<2x0x1xi8> {
  ^
<stdin>:4:10: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"llvm", "embedded-elf-x86_64", {data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
    %0 = "mhlo.dynamic-slice"(%arg0, %arg1, %arg2, %arg3) {slice_sizes = dense<[2, 0, 1]> : tensor<3xi64>} : (tensor<7x5x3xi8>, tensor<i32>, tensor<i32>, tensor<i32>) -> tensor<2x0x1xi8>
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<7x5x3xi8>, %arg1: tensor<i32>, %arg2: tensor<i32>, %arg3: tensor<i32>) -> tensor<2x0x1xi8> {
  ^
<stdin>:4:10: error: failed to serialize executables
    %0 = "mhlo.dynamic-slice"(%arg0, %arg1, %arg2, %arg3) {slice_sizes = dense<[2, 0, 1]> : tensor<3xi64>} : (tensor<7x5x3xi8>, tensor<i32>, tensor<i32>, tensor<i32>) -> tensor<2x0x1xi8>
         ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<7x5x3xi8>, %arg1: tensor<i32>, %arg2: tensor<i32>, %arg3: tensor<i32>) -> tensor<2x0x1xi8> {
  ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by jpienaar** [comment]
Passing at head.
