### ISSUE TITLE
`'std.call' op operand type mismatch: expected operand type '!hal.buffer_view', but provided 'tensor<f32>' `

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#7651]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<f32>) -> tensor<f32> {
    %0:2 = call @"jit_jvp(f)"(%arg0) : (tensor<f32>) -> (tensor<f32>, tensor<f32>)
    %1 = mhlo.constant dense<1.000000e+00> : tensor<f32>
    %2 = call @"jit_transpose(jvp(f))"(%0#1, %1) : (tensor<f32>, tensor<f32>) -> tensor<f32>
    return %2 : tensor<f32>
  }
  func @"jit_jvp(f)"(%arg0: tensor<f32>) -> (tensor<f32>, tensor<f32>) {
    %0 = mhlo.multiply %arg0, %arg0 : tensor<f32>
    return %0, %arg0 : tensor<f32>, tensor<f32>
  }
  func @"jit_transpose(jvp(f))"(%arg0: tensor<f32>, %arg1: tensor<f32>) -> tensor<f32> {
    %0 = mhlo.multiply %arg0, %arg1 : tensor<f32>
    %1 = mhlo.multiply %arg1, %arg0 : tensor<f32>
    %2 = mhlo.add %1, %0 : tensor<f32>
    return %2 : tensor<f32>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python q.py
Traceback (most recent call last):
  File "/home/phawkins/jax/q.py", line 25, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/home/phawkins/.pyenv/versions/py39/lib/python3.9/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/home/phawkins/.pyenv/versions/py39/lib/python3.9/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:4:12: error: 'std.call' op operand type mismatch: expected operand type '!hal.buffer_view', but provided 'tensor<f32>' for operand number 0
    %0:2 = call @"jit_jvp(f)"(%arg0) : (tensor<f32>) -> (tensor<f32>, tensor<f32>)
           ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /home/phawkins/.pyenv/versions/py39/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/home/phawkins/.pyenv/versions/py39/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

The IR looks legal to me, but perhaps I'm missing something.

**Comment by benvanik** [comment]
mark the internal functions private - only main() should be public (the default in MLIR if you don't specify)

**Comment by hawkinsp** [comment]
Yup, that seems to work. But... it's not a great error.

**Comment by benvanik** [comment]
agreed
