### ISSUE TITLE
Error running dot_general with matrices with dynamic dimensions

### ISSUE THREAD

**Issue by gnecula** [google/iree#7889]
This is from experiments with JAX+IREE and dynamic shapes. I am running into errors with a dot_general for matrices with dynamic dimensions.

Repro:
```
    from iree.compiler import compile_str

    CODE = """
module @jit_f.3  {
  func public @main(%arg0: tensor<?x?xf32> {mhlo.is_same_data_across_replicas} loc(unknown)) -> tensor<?x?xf32> {
    %3 = "mhlo.dot_general"(%arg0, %arg0) {dot_dimension_numbers = #mhlo.dot<lhs_contracting_dimensions = [1], rhs_contracting_dimensions = [0]>, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<?x?xf32>, tensor<?x?xf32>) -> tensor<?x?xf32>
    return %3 : tensor<?x?xf32>
  }
}
    """

    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Error is:
```
>         raise CompilerToolError(process)
E         iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
E         Diagnostics:
E         <stdin>:2:1: error: conversion from source -> vm failed
E         module @jit_f.3  {
E         ^
E         
E         
E         Invoked with:
E          ireec /Users/necula/.pyenv/versions/jax39/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/necula/.pyenv/versions/jax39/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by stellaraccident** [comment]
I know we accept that form from pytorch so likely a problem with the MHLO lowerings. Also the error message (or lack thereof) is part of the bug.

**Comment by GMNGeoffrey** [comment]
Hmmm I would expect there to also be diagnostics about which specific pass failed. Can you post the full log somewhere? I also wonder if these are generated, but not correctly surfaced through Python

**Comment by gnecula** [comment]
The following is literally everything that is printed when I copy the repro above in `t.py` and run it. Should I run with additional flags or environment to get more logging? 
```
$ python tests/t.py
Traceback (most recent call last):
  File "/Users/necula/Source/jax/tests/t.py", line 12, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/Users/necula/.pyenv/versions/jax39/lib/python3.9/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/Users/necula/.pyenv/versions/jax39/lib/python3.9/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:2:1: error: conversion from source -> vm failed
module @jit_f.3  {
^


Invoked with:
 ireec /Users/necula/.pyenv/versions/jax39/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/necula/.pyenv/versions/jax39/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by GMNGeoffrey** [comment]
Then Stella's right: the fact that the error message suck is also a bug :-D I don't know of any extra flags or configurations

**Comment by burmako** [comment]
@gnecula I've debugged this as follows:

```
$ iree-opt --iree-mhlo-input-transformation-pipeline --print-ir-after-all --mlir-disable-threading dot_general.mlir
...
// -----// IR Dump After MHLOToMHLOPreprocessing Failed //----- //
"builtin.func"() ({
^bb0(%arg0: tensor<?x?xf32>):  // no predecessors
  %0 = "mhlo.dot_general"(%arg0, %arg0) {dot_dimension_numbers = #mhlo.dot<lhs_contracting_dimensions = [1], rhs_contracting_dimensions = [0]>, precision_config = ["DEFAULT", "DEFAULT"]} : (tensor<?x?xf32>, tensor<?x?xf32>) -> tensor<?x?xf32>
  "std.return"(%0) : (tensor<?x?xf32>) -> ()
}) {arg_attrs = [{mhlo.is_same_data_across_replicas}], sym_name = "main", sym_visibility = "public", type = (tensor<?x?xf32>) -> tensor<?x?xf32>} : () -> ()
```

Since the MHLOToMHLOPreprocessing pass is based on the dialect conversion framework, having see this dump, I reran `iree-opt` with `--debug-only=dialect-conversion`, expecting to see a confirmation that a particular pattern was problematic. Unfortunately, nothing was printed, and I'm not sure why (perhaps `applyPatternsAndFoldGreedily` doesn't use the additional flag in question?).

Anyway, reading the code of the pass eventually revealed the culprit - the pass that lowers dot_general to a combination of reshape, transpose and dot. That pass wasn't written with dynamic shapes in mind: https://github.com/tensorflow/mlir-hlo/blob/9ec54804459fd6d8c47dec22bc22d32f82ec4fee/lib/Dialect/mhlo/transforms/lower_general_dot.cc#L151.

**Comment by burmako** [comment]
@rsuderman Thank you for your CL that fixes the handling of dynamically-shaped dot_general: https://github.com/tensorflow/mlir-hlo/pull/26. I'm reviewing it in Critique right now.

**Comment by rsuderman** [comment]
Verified this compiles at head for IREE.
