### ISSUE TITLE
MHLO lowering fails for mixed-precision mhlo.dot_general

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#9289]
Repro:
```
import iree.compiler

CODE = """
#loc0 = loc(unknown)
module @jit_prim_fun.0 {
  func.func public @main(%arg0: tensor<3xf16> loc(unknown), %arg1: tensor<3xf16> loc(unknown)) -> tensor<f32> {
    %0 = "mhlo.dot_general"(%arg0, %arg1) {dot_dimension_numbers = #mhlo.dot<lhs_contracting_dimensions = [0], rhs_contracting_dimensions = [0]>, precision_config = [#mhlo<"precision DEFAULT">, #mhlo<"precision DEFAULT">]} : (tensor<3xf16>, tensor<3xf16>) -> tensor<f32> loc(#loc1)
    return %0 : tensor<f32> loc(#loc0)
  } loc(#loc0)
} loc(#loc0)
#loc1 = loc("jit(dot_general)/jit(main)/dot_general[dimension_numbers=(((0,), (0,)), ((), ())) precision=None preferred_element_type=float32]"("/Users/phawkins/p/jax/tests/lax_test.py":1103:1))
"""

iree_binary = iree.compiler.compile_str(
    CODE, target_backends=["dylib"], input_type="mhlo")
```

Output:
```
Traceback (most recent call last):
  File "/Users/phawkins/p/jax/t.py", line 14, in <module>
    iree_binary = iree.compiler.compile_str(
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/core.py", line 293, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/binaries.py", line 200, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
/Users/phawkins/p/jax/tests/lax_test.py:1103:1: error: 'mhlo.reshape' op requires the same element type for all operands and results
       (dtype == np.complex128 or preferred_element_type == np.complex128)):
^
compilation failed


Invoked with:
 iree-compile /Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
```

**Comment by jpienaar** [comment]
```
./tools/iree-compile /tmp/9289.mlir  --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false -o /dev/null
```

works locally. Marking as closed.
