### ISSUE TITLE
CUDA_ERROR_INVALID_HANDLE from cuLaunchKernel possibly related to CUDA context handling

### ISSUE THREAD

**Issue by hawkinsp** [google/iree#9515]
### What happened?

The attached Python program which mixes TF and IREE, when run, produces:

```
$ python q.py
15
2022-06-15 15:21:39.632455: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
Traceback (most recent call last):
  File "/usr/local/google/home/phawkins/p/jax/q.py", line 35, in <module>
    print(np.asarray(module["main"](x, y)))
  File "/usr/local/google/home/phawkins/.pyenv/versions/py3.10.4/lib/python3.10/site-packages/iree/runtime/function.py", line 129, in __call__
    self._invoke(arg_list, ret_list)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py3.10.4/lib/python3.10/site-packages/iree/runtime/function.py", line 153, in _invoke
    self._vm_context.invoke(self._vm_function, arg_list, ret_list)
RuntimeError: Error invoking function: /main_checkout/iree/runtime/src/iree/hal/cuda/stream_command_buffer.c:369: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_HANDLE' (400): invalid resource handle; cuLaunchKernel; while invoking native function hal.ex.submit_and_wait; while calling import;
[ 1]   native hal.ex.submit_and_wait:0 -
[ 0] bytecode jit__lambda__2.main:470 <stdin>:3:3
```

I have a hypothesis as to what's going wrong, namely that in this program two libraries (IREE and TF) are both using the same thread to manipulate the CUDA context. TF changes the CUDA context and IREE does not gracefully handle that!

TF has logic to save and restore the context:
https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/stream_executor/cuda/cuda_driver.cc;drc=fdfdc02affbcd7e76a293f7f89871614ec8fa316;l=142

however note that it does not try to restore the original caller's CUDA context on error.

In the spirit of being liberal in what we accept, IREE should tolerate having other libraries change the CUDA context.

### Steps to reproduce your issue

```
import iree.compiler
import iree.runtime

import numpy as np

import tensorflow as tf

ir = """
module @jit__lambda_.2 {
  func.func public @main(%arg0: tensor<i32>, %arg1: tensor<i32>) -> tensor<i32> {
    %0 = mhlo.add %arg0, %arg1 : tensor<i32>
    return %0 : tensor<i32>
  }
}
"""

config = iree.runtime.system_api.Config("cuda")
bin = iree.compiler.compile_str(ir, target_backends=["cuda"], input_type="mhlo")
vm_module = iree.runtime.VmModule.from_flatbuffer(bin)
module = iree.runtime.load_vm_module(vm_module, config)

x = np.array(7, dtype=np.int32)
y = np.array(8, dtype=np.int32)

print(np.asarray(module["main"](x, y)))


tf.add(1, 2)


vm_module = iree.runtime.VmModule.from_flatbuffer(bin)
module = iree.runtime.load_vm_module(vm_module, config)

print(np.asarray(module["main"](x, y)))
```

### What component(s) does this issue relate to?

Runtime

### Version information

```
$ pip show iree-compiler iree-runtime tensorflow
Name: iree-compiler
Version: 20220523.147
Summary: IREE Compiler API
Home-page:
Author: IREE Authors
Author-email: iree-discuss@googlegroups.com
License: Apache-2.0
Location: /usr/local/google/home/phawkins/.pyenv/versions/3.10.4/envs/py3.10.4/lib/python3.10/site-packages
Requires: numpy, PyYAML
Required-by:
---
Name: iree-runtime
Version: 20220523.147
Summary: IREE Python Runtime Components
Home-page: https://github.com/google/iree
Author: IREE Authors
Author-email: iree-discuss@googlegroups.com
License: Apache-2.0
Location: /usr/local/google/home/phawkins/.pyenv/versions/3.10.4/envs/py3.10.4/lib/python3.10/site-packages
Requires: numpy, PyYAML
Required-by:
---
Name: tensorflow
Version: 2.9.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/google/home/phawkins/.pyenv/versions/3.10.4/envs/py3.10.4/lib/python3.10/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, keras-preprocessing, libclang, numpy, opt-einsum, packaging, protobuf, setuptools, six, tensorboard, tensorflow-estimator, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wrapt
Required-by:
```

**Comment by stellaraccident** [comment]
Thanks, Peter for the report and the theory. So your recommendation is to defensively save/set the context prior to making CUDA calls, correct?

**Comment by benvanik** [comment]
yep - #9301 is tracking that

**Comment by alliemartens** [comment]
Closing as #9301 is tracking this already. Please re open if needed!
